import type { Metadata } from 'next'

import StyledComponentsRegistry from '@menu-master-app/lib/registry'
import './globals.css'
import { ThemeProvider } from 'styled-components'
import { GlobalStyles } from './global'
import { DefaultTheme } from '@menu-master-app/styles/themes/default'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
  children: React.ReactNode;
}) {
	return (
		<html lang="pt-br">
			<body>
				<StyledComponentsRegistry>
					<ThemeProvider theme={DefaultTheme}>
						<GlobalStyles />
						{children}
					</ThemeProvider>
				</StyledComponentsRegistry>
			</body>
		</html>
	)
}
